# 📘 Pre-entrega

**Nombre del alumno:** Enrique José Escalante Echagüe

## 🧩 Etapa 1: Recopilación y Preparación de Datos
**Objetivo:** Demostrar habilidades en Python, familiaridad con el entorno de trabajo y conocimientos básicos sobre manipulación de datos.

### 1️⃣ Carga de datos

In [2]:
# TODO: Cargar los datasets como DataFrames usando pandas.
import pandas as pd
import numpy as np
# Montar el drive
from google.colab import drive
drive.mount('/content/drive')
# Verificar que los archivos csv se encuentren en la carpeta datasets
import os
os.listdir("/content/drive/MyDrive/Tech/datasets")

Mounted at /content/drive

['ventas.csv', 'clientes.csv', 'marketing.csv', 'ventas.xlsx']

In [3]:
# Verificar que los archivos csv se encuentren en la carpeta datasets
import os
os.listdir("/content/drive/MyDrive/Tech/datasets")

['ventas.csv', 'clientes.csv', 'marketing.csv', 'ventas.xlsx']

In [4]:
# Rutas de archivos
ruta_ventas = "/content/drive/MyDrive/Tech/datasets/ventas.csv"
ruta_clientes = "/content/drive/MyDrive/Tech/datasets/clientes.csv"
ruta_marketing = "/content/drive/MyDrive/Tech/datasets/marketing.csv"

In [15]:
# Sugerencia: utilizar pd.read_csv() para cargar los archivos CSV.
ventas = pd.read_csv(ruta_ventas)
clientes = pd.read_csv(ruta_clientes)
marketing = pd.read_csv(ruta_marketing)

print("Archivos cargados exitosamente\n")

In [14]:
# Recordá verificar la ruta correcta y revisar las primeras filas con .head().
# Validamos formas para comprobar la ruta correcta.
# Reporte de carga
datasets = {
  'Ventas': ventas,
  'Clientes': clientes,
  'Marketing': marketing
}

for nombre, df in datasets.items():
  print(f"{nombre:12} -> {df.shape[0]:>5,} filas × {df.shape[1]:>2} columnas")

print("\n" + "-"*80)
print("Primeras filas de cada dataset:")
print("-"*80)

for nombre, df in datasets.items():
    print(f"--- {nombre} ---")
    display(df.head())

Archivos cargados exitosamente

Ventas       -> 3,035 filas ×  6 columnas
Clientes     ->   567 filas ×  5 columnas
Marketing    ->    90 filas ×  6 columnas

--------------------------------------------------------------------------------
Primeras filas de cada dataset:
--------------------------------------------------------------------------------
--- Ventas ---

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

--- Clientes ---

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

--- Marketing ---

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

In [7]:
# Revisar primeras filas con .head().
display(ventas.head(3))
display(clientes.head(3))
display(marketing.head(3))

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024

### 2️⃣ Análisis exploratorio inicial

In [50]:
# TODO: Realizar un análisis exploratorio inicial de los DataFrames.
# Sugerencia: usar métodos como .info(), .describe(), .shape y .columns. dtypes.
def eda(df, nombre):
    print(f"\n{'─'*80}")
    print(f"DATASET: {nombre}")
    print(f"{'─'*80}")
    # Información general
    print(f"Dimensiones: {df.shape[0]:,} filas × {df.shape[1]} columnas")
    print("columnas:", list(df.columns))
    # Tipos de datos
    print("\nTipos de Datos:")
    tipo_counts = df.dtypes.value_counts()
    for tipo, count in tipo_counts.items():
        print(f"- {tipo}: {count} columnas")
    print("dtypes:")
    print(df.dtypes)
    # Análisis de nulos
    nulos = df.isna().sum()
    if nulos.sum() > 0:
        print("\nValores Nulos Detectados:")
        nulos_pct = (nulos / len(df) * 100).round(2)
        for col in nulos[nulos > 0].index:
            print(f"- {col}: {nulos[col]}")
    else:
        print("Sin valores nulos")
    # Muestra de datos
    print("\nPrimeras filas:")
    display(df.head(5))
    # Estadísticas descriptivas
    print("\nDescribe (numérico):")
    display(df.describe(include='number'))
    print(f"\n{'─'*80}\n")

In [51]:
eda(ventas, "VENTAS (inicial)")

────────────────────────────────────────────────────────────────────────────────
DATASET: VENTAS (inicial)
────────────────────────────────────────────────────────────────────────────────
Dimensiones: 3,035 filas × 6 columnas
columnas: ['id_venta', 'producto', 'precio', 'cantidad', 'fecha_venta', 'categoria']

Tipos de Datos:
- object: 4 columnas
- int64: 1 columnas
- float64: 1 columnas
dtypes:
id_venta         int64
producto        object
precio          object
cantidad       float64
fecha_venta     object
categoria       object
dtype: object

Valores Nulos Detectados:
- precio: 2
- cantidad: 2

Primeras filas:

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

Describe (numérico):

          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000

────────────────────────────────────────────────────────────────────────────────

In [56]:
eda(clientes, "CLIENTES (inicial)")

────────────────────────────────────────────────────────────────────────────────
DATASET: CLIENTES (inicial)
────────────────────────────────────────────────────────────────────────────────
Dimensiones: 567 filas × 5 columnas
columnas: ['id_cliente', 'nombre', 'edad', 'ciudad', 'ingresos']

Tipos de Datos:
- int64: 2 columnas
- object: 2 columnas
- float64: 1 columnas
dtypes:
id_cliente      int64
nombre         object
edad            int64
ciudad         object
ingresos      float64
dtype: object
Sin valores nulos

Primeras filas:

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

Describe (numérico):

       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000

────────────────────────────────────────────────────────────────────────────────

In [53]:
eda(marketing, "MARKETING (inicial)")

────────────────────────────────────────────────────────────────────────────────
DATASET: MARKETING (inicial)
────────────────────────────────────────────────────────────────────────────────
Dimensiones: 90 filas × 6 columnas
columnas: ['id_campanha', 'producto', 'canal', 'costo', 'fecha_inicio', 'fecha_fin']

Tipos de Datos:
- object: 4 columnas
- int64: 1 columnas
- float64: 1 columnas
dtypes:
id_campanha       int64
producto         object
canal            object
costo           float64
fecha_inicio     object
fecha_fin        object
dtype: object
Sin valores nulos

Primeras filas:

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

Describe (numérico):

       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000

────────────────────────────────────────────────────────────────────────────────

In [ ]:

# Esto te ayudará a entender la estructura y el contenido de los datos.
# Podés incluir comentarios sobre observaciones iniciales.

### 3️⃣ Calidad de los datos

In [76]:
# TODO: Identificar valores nulos y duplicados en los conjuntos de datos.
# Sugerencia: usar .isna().sum() y .duplicated().sum().
# Documentar las observaciones con print() o comentarios.
def calidad(df, nombre, clave=None):
    # Mostrar título descriptivo con el nombre del DF
    print(f"\n{'─'*80}")
    print(f"🔍 CALIDAD: {nombre}")
    print(f"{'─'*80}")
    # Nulos
    print(f"\nValores Nulos:")
    nulos_df = df.isna().sum().to_frame('cantidad')
    display(nulos_df)
    # Duplicados
    dup_completos = df.duplicated(keep=False).sum()
    print(f"\nFilas Duplicadas (completas): {dup_completos} - {dup_completos/len(df)*100:.2f}% del dataset")
    # Duplicados por clave
    if clave and clave in df.columns:
        dup_clave = df[clave].duplicated(keep=False).sum()
        print(f"\nDuplicados en clave '{clave}': {dup_clave}")

        if dup_clave > 0:
            # Mostrar los valores más duplicados
            top_dups = (
                df[df[clave].duplicated(keep=False)][clave]
                .value_counts()
                .head(5)
            )
            print(f"\nLos 5 valores más duplicados:")
            for valor, count in top_dups.items():
                print(f"- {valor}: {count} veces")
    print(f"{'─'*80}\n")

In [77]:
calidad(ventas, "VENTAS", clave="id_venta")

────────────────────────────────────────────────────────────────────────────────
🔍 CALIDAD: VENTAS
────────────────────────────────────────────────────────────────────────────────

Valores Nulos:

             cantidad
id_venta            0
producto            0
precio              2
cantidad            2
fecha_venta         0
categoria           0

Filas Duplicadas (completas): 70 - 2.31% del dataset

Duplicados en clave 'id_venta': 70

Los 5 valores más duplicados:
- 56: 2 veces
- 421: 2 veces
- 424: 2 veces
- 1868: 2 veces
- 2545: 2 veces
────────────────────────────────────────────────────────────────────────────────

In [78]:
calidad(clientes, "CLIENTES", clave="id_cliente")

────────────────────────────────────────────────────────────────────────────────
🔍 CALIDAD: CLIENTES
────────────────────────────────────────────────────────────────────────────────

Valores Nulos:

            cantidad
id_cliente         0
nombre             0
edad               0
ciudad             0
ingresos           0

Filas Duplicadas (completas): 0 - 0.00% del dataset

Duplicados en clave 'id_cliente': 0
────────────────────────────────────────────────────────────────────────────────

In [79]:
calidad(marketing, "MARKETING", clave="id_campanha")

────────────────────────────────────────────────────────────────────────────────
🔍 CALIDAD: MARKETING
────────────────────────────────────────────────────────────────────────────────

Valores Nulos:

              cantidad
id_campanha          0
producto             0
canal                0
costo                0
fecha_inicio         0
fecha_fin            0

Filas Duplicadas (completas): 0 - 0.00% del dataset

Duplicados en clave 'id_campanha': 0
────────────────────────────────────────────────────────────────────────────────

## 🧹 Etapa 2: Preprocesamiento y Limpieza de Datos
**Objetivo:** Demostrar conocimiento de las técnicas de limpieza y transformación de datos.

### 4️⃣ Limpieza de datos

In [86]:
# TODO: Limpiar el conjunto de datos eliminando duplicados y caracteres no deseados.
# Crear Copias para trabajar
ventas_clean = ventas.copy()
clientes_clean = clientes.copy()
marketing_clean = marketing.copy()

In [87]:
# Sugerencia: aplicar .drop_duplicates(), .str.strip(), .str.replace() según el caso.
# Eliminar filas completamente duplicadas
for nombre, df in [('Ventas', ventas_clean), ('Clientes', clientes_clean), ('Marketing', marketing_clean)]:
    antes = len(df)
    if nombre == 'Ventas':
        ventas_clean = ventas_clean.drop_duplicates()
        despues = len(ventas_clean)
    elif nombre == 'Clientes':
        clientes_clean = clientes_clean.drop_duplicates()
        despues = len(clientes_clean)
    else:
        marketing_clean = marketing_clean.drop_duplicates()
        despues = len(marketing_clean)

    eliminados = antes - despues
    if eliminados > 0:
        print(f"- {nombre:12}: {eliminados:>4} duplicados eliminados ({eliminados/antes*100:.2f}%)")
    else:
        print(f"- {nombre:12}: Sin duplicados")
# Documentar el proceso y los resultados.

- Ventas      :   35 duplicados eliminados (1.15%)
- Clientes    : Sin duplicados
- Marketing   : Sin duplicados

In [101]:
# Normalizar fechas
fechas_convertidas = 0
for df in [ventas_clean, clientes_clean, marketing_clean]:
    for col in df.columns:
        if "fecha" in col.lower():  # detecta columnas con la palabra "fecha"
            df[col] = pd.to_datetime(df[col], errors="coerce", dayfirst=True)
            fechas_convertidas += 1

if fechas_convertidas > 0:
    print(f"{fechas_convertidas} columnas de fecha normalizadas")
else:
    print("No se encontraron columnas de fecha para normalizar")

3 columnas de fecha normalizadas

In [88]:
#Normalizar Textos
# Función para limpiar texto en columnas tipo string
def normalizar_texto(df):
    for col in df.select_dtypes(include='object').columns:
        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
            .str.replace(r'[\u200b\t\r\n]', '', regex=True)
            .str.replace(r'\s+', ' ', regex=True)
            .str.title()
        )
    return df

ventas_clean = normalizar_texto(ventas_clean)
clientes_clean = normalizar_texto(clientes_clean)
marketing_clean = normalizar_texto(marketing_clean)

In [119]:
# Normalizar valores numéricos
# precio
if "precio" in ventas_clean.columns:
    ventas_clean["precio"] = (
        ventas_clean["precio"]
        .astype(str)                        # Convierte todo a texto
        .str.replace("$", "", regex=False)  # Elimina el símbolo $
        .str.replace(",", "", regex=False)  # Elimina comas de miles 1,000  1000
        .str.strip()                        # Quita espacios sobrantes
    )
    ventas_clean["precio"] = pd.to_numeric(ventas_clean["precio"], errors="coerce")
# Cantidad
if "cantidad" in ventas_clean.columns:
    ventas_clean["cantidad"] = pd.to_numeric(ventas_clean["cantidad"], errors="coerce").astype("Int64")

In [ ]:
# Guardar datos limpios como CSV
#print(ventas_clean.head())
#print(clientes_clean.head())
#print(marketing_clean.head())
ventas_clean.info()
ventas_clean.to_csv("ventas_clean.csv", index=False)
clientes_clean.to_csv("clientes_clean.csv", index=False)
marketing_clean.to_csv("marketing_clean.csv", index=False)

print("✅ Archivos guardados: ventas_clean.csv, clientes_clean.csv, marketing_clean.csv")

In [115]:
# Reporte
def reporte_limpieza(df_antes, df_despues, nombre):
    """Compara estado antes/después de limpieza"""
    print("\n" + "-"*80)
    print("📊 REPORTE DE LIMPIEZA")
    print("-"*80)
    print(f"\n{nombre}:")
    print(f"   Registros antes:  {len(df_antes):>6,}")
    print(f"   Registros después: {len(df_despues):>6,}")
    print(f"   Eliminados:        {len(df_antes) - len(df_despues):>6,} ({(1-len(df_despues)/len(df_antes))*100:.2f}%)")

    nulos_antes = df_antes.isna().sum().sum()
    nulos_despues = df_despues.isna().sum().sum()
    print(f"   Nulos antes:       {nulos_antes:>6,}")
    print(f"   Nulos eliminados:  {nulos_antes - nulos_despues:>6,}")


    print("\n" + "-"*80)

In [116]:
reporte_limpieza(ventas, ventas_clean, "Ventas")

--------------------------------------------------------------------------------
📊 REPORTE DE LIMPIEZA
--------------------------------------------------------------------------------

Ventas:
   Registros antes:   3,035
   Registros después:  3,000
   Eliminados:            35 (1.15%)
   Nulos antes:            4
   Nulos eliminados:       2

--------------------------------------------------------------------------------

In [114]:
reporte_limpieza(clientes, clientes_clean, "Clientes")

--------------------------------------------------------------------------------
📊 REPORTE DE LIMPIEZA
--------------------------------------------------------------------------------

Clientes:
   Registros antes:     567
   Registros después:    567
   Eliminados:             0 (0.00%)
   Nulos antes:            0
   Nulos después:          0
   Nulos eliminados:       0

--------------------------------------------------------------------------------

In [117]:
reporte_limpieza(marketing, marketing_clean, "Marketing")

--------------------------------------------------------------------------------
📊 REPORTE DE LIMPIEZA
--------------------------------------------------------------------------------

Marketing:
   Registros antes:      90
   Registros después:     90
   Eliminados:             0 (0.00%)
   Nulos antes:            0
   Nulos eliminados:       0

--------------------------------------------------------------------------------

### 5️⃣ Transformación de datos

In [ ]:
# TODO: Aplicar filtros y transformaciones para crear una tabla de ventas

In [130]:
# Detectar columna de producto
def encontrar_columna(df, candidatos):
    for c in df.columns:
        if any(p in c.lower() for p in candidatos):
            return c
    return None

prod_col = encontrar_columna(ventas_clean, ['producto', 'id_producto', 'sku'])

if prod_col is None:
    print("No se encontró columna de producto")
else:
    print(f"Columna detectada: '{prod_col}'")

# Calcular ingreso
print("\nCálculo de Ingreso por Registro")
ventas_perf = ventas_clean.assign(
    ingreso=ventas_clean['precio'] * ventas_clean['cantidad']
)
print(f"- Nueva columna 'ingreso' = precio × cantidad")
print(f"- Ingreso total: ${ventas_perf['ingreso'].sum():,.2f}")

# Agregar por producto
print("\nAgregación por Producto")
resumen_prod = (
    ventas_perf
    .groupby(by=prod_col, dropna=False, as_index=False)
    .agg(
        registros=('ingreso', 'size'),
        unidades=('cantidad', 'sum'),
        precio_promedio=('precio', 'mean'),
        ingreso_total=('ingreso', 'sum')
    )
)
print(f"- {len(resumen_prod)} productos únicos procesados")

# que muestre solo los productos con alto rendimiento. calcular el percentil 80
# y filtrar los productos que superen ese umbral en ventas.
#quantile(0.8)
# Sugerencia: usar .query() o condiciones con operadores lógicos.

# Calcular percentil 80
print("\nCálculo del Percentil 80")
p80_ingreso = resumen_prod['ingreso_total'].quantile(0.80, interpolation='linear')
print(f"- Percentil 80: ${p80_ingreso:,.2f}")
print(f"- El 20% superior de productos genera ≥ ${p80_ingreso:,.2f}")

# Filtrar alto rendimiento
print("\nFiltrado y Clasificación")
ventas_top = (
    resumen_prod
    .query("ingreso_total >= @p80_ingreso", engine='python')
    .sort_values(by=['ingreso_total', 'unidades'], ascending=[False, False], ignore_index=True)
)

print(f"- {len(ventas_top)} productos clasificados como 'Alto Rendimiento'")
print(f"- Representan: {len(ventas_top)/len(resumen_prod)*100:.1f}% del catálogo")

# Calcular participación
total_ingresos = resumen_prod['ingreso_total'].sum()
ingresos_top = ventas_top['ingreso_total'].sum()
print(f"   Generan: ${ingresos_top:,.2f} ({ingresos_top/total_ingresos*100:.1f}% del total)")

# Mostrar resultados
print("PRODUCTOS - ALTO RENDIMIENTO")
print("="*80)
display(ventas_top.head(10))

# Insight clave
print(f"El {len(ventas_top)/len(resumen_prod)*100:.0f}% de productos generan el {ingresos_top/total_ingresos*100:.0f}% de los ingresos totales")

Columna detectada: 'producto'

Cálculo de Ingreso por Registro
- Nueva columna 'ingreso' = precio × cantidad
- Ingreso total: $1,467,093.52

Agregación por Producto
- 30 productos únicos procesados

Cálculo del Percentil 80
- Percentil 80: $52,518.85
- El 20% superior de productos genera ≥ $52,518.85

Filtrado y Clasificación
- 6 productos clasificados como 'Alto Rendimiento'
- Representan: 20.0% del catálogo
   Generan: $397,052.20 (27.1% del total)
PRODUCTOS - ALTO RENDIMIENTO
================================================================================

            producto  registros  unidades  precio_promedio  ingreso_total
0    Lámpara De Mesa        176      1112        72.720625       82276.38
1        Auriculares        143       958        76.302727       74175.58
2         Microondas        135       912        79.176000       72562.89
3           Cafetera        117       765        79.046581       59607.31
4  Cuadro Decorativo        100       726        74.578000        54297.6
5         Smartphone        101       665        81.398416       54132.44

El 20% de productos generan el 27% de los ingresos totales

### 6️⃣ Agregación

In [ ]:
# TODO: Resumir las ventas por categoría de producto y analizar los ingresos generados.
# Sugerencia: usar .groupby() y .agg() para generar métricas como suma y promedio.

In [147]:
print("AGREGACIÓN - ANÁLISIS POR CATEGORÍA")
print("="*80)

# Detectar columna categoría
cat_col = encontrar_columna(ventas_clean, ['categoria', 'categoría', 'rubro'])

if cat_col is None:
    print("No se encontró columna de categoría")
else:
    print(f"Columna detectada: '{cat_col}'\n")

# Asegurar columna ingreso
if 'ingreso' not in ventas_clean.columns:
    ventas_cat = ventas_clean.assign(ingreso=ventas_clean['precio'] * ventas_clean['cantidad'])
else:
    ventas_cat = ventas_clean.copy()

# Agregación
print("Agregación de Métricas por Categoría")
resumen_cat = (
    ventas_cat
    .groupby(by=cat_col, dropna=False, as_index=False)
    .agg(
        ventas=('ingreso', 'size'),
        unidades=('cantidad', 'sum'),
        precio_promedio=('precio', 'mean'),
        ingreso_total=('ingreso', 'sum')
    )
    .sort_values(by='ingreso_total', ascending=False, na_position='last', ignore_index=True)
)

# Calcular ticket promedio
resumen_cat['ticket_promedio_por_venta'] = resumen_cat['ingreso_total'] / resumen_cat['ventas']

# Calcular participación
resumen_cat['participacion_%'] = (resumen_cat['ingreso_total'] / resumen_cat['ingreso_total'].sum() * 100).round(2)

print(f"- {len(resumen_cat)} categorías analizadas\n")

# Mostrar resultados

print("RESUMEN POR CATEGORÍA")
display(resumen_cat)

# Análisis e insights
print("\nANÁLISIS DE PARTICIPACIÓN")

for idx, row in resumen_cat.iterrows():
    categoria = row[cat_col]
    participacion = row['participacion_%']
    ticket = row['ticket_promedio_por_venta']

    print(f"{categoria}")
    print(f"- Participación: {participacion}%")
    print(f"- Ticket promedio: ${ticket:,.2f}")
    print(f"- Unidades vendidas: {row['unidades']:,}")

# Recomendaciones
print("\nRECOMENDACIONES ESTRATÉGICAS")
# Identificar categoría con mejor ticket
mejor_ticket = resumen_cat.loc[resumen_cat['ticket_promedio_por_venta'].idxmax()]
print(f"- Mayor ticket promedio: '{mejor_ticket[cat_col]}' (${mejor_ticket['ticket_promedio_por_venta']:,.2f})")

AGREGACIÓN - ANÁLISIS POR CATEGORÍA
================================================================================
Columna detectada: 'categoria'

Agregación de Métricas por Categoría
- 3 categorías analizadas

RESUMEN POR CATEGORÍA

,categoria,ventas,unidades,precio_promedio,ingreso_total,ticket_promedio_por_venta,participacion_%
0,Electrodomésticos,1000,6592,76.52096,505299.63,505.29963,34.44
1,Electrónica,999,6413,75.25492,482577.8,483.060861,32.89
2,Decoración,1001,6490,74.09800,479216.09,478.737353,32.66

ANÁLISIS DE PARTICIPACIÓN
Electrodomésticos
- Participación: 34.44%
- Ticket promedio: $505.30
- Unidades vendidas: 6,592
Electrónica
- Participación: 32.89%
- Ticket promedio: $483.06
- Unidades vendidas: 6,413
Decoración
- Participación: 32.66%
- Ticket promedio: $478.74
- Unidades vendidas: 6,490

RECOMENDACIONES ESTRATÉGICAS
- Mayor ticket promedio: 'Electrodomésticos' ($505.30)

### 7️⃣ Integración de datos, opcional, NO OBLIGATORIO

In [ ]:
# TODO: Combinar los sets de datos de ventas y marketing para obtener una visión más amplia de las tendencias.
# Sugerencia: usar pd.merge() especificando la clave común entre ambos DataFrames.
# Documentar cualquier observación relevante sobre la combinación de datos.